---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dp-app
  name: "dp-app-$BUILD_NUMBER"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-app
  template:
    metadata:
      labels:
        app: dp-app
    spec:
      containers:
        - image: ssergeya/dp_app:nginx0.1.$BUILD_NUMBER
          name: app-nginx
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dp-app
  name: "dp-app-svc"
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http
      nodePort: 30033
  selector:
    app: dp-app
  type: NodePort
