---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dp-app
  name: "dp-app-svc"
spec:
  serviceAccountName: jenkins
  ports:
    - name: "http"
      port: 80
      targetPort: http
      nodePort: 30033
  selector:
    app: dp-app
  type: NodePort
